org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.cleannrooster.visceral_combat
archives_base_name=visceral_combat
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21
cloth_config_version=15.0.130
player_anim_version=2.0.0-alpha1+1.21

# Dependencies
fabric_version=0.116.0+1.21.1
