org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.11
loom_version=1.5-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.cleannrooster.visceral_combat
archives_base_name=visceral_combat
cloth_config_version=11.1.118
player_anim_version=1.0.2-rc1+1.20

# Dependencies
fabric_version=0.92.2+1.20.1
